version: "3.8"

services:
  app:
    build: .
    container_name: players-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    # environment:  # Optional: You can remove this if using .env only
    #   - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    command: redis-server --appendonly yes
    ports:
      - "6379:6379" # ✅ corrected port
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
